server:
  port: 8080
  servlet:
    context-path: /api
    
management:
  endpoints:
    enabled-by-default: true
    health:
      enabled: true
    web.exposure.include: health,info

spring:
  application:
    name: CLIENT-SERVICE
  threads:
    virtual:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

